###################################################
#      Made by João Pedro Vicente Pansiere        #
###################################################
version: "3.1"
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./.mysql-data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      environment_network:
        ipv4_address: 172.30.0.2

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/laravel.conf
    ports:
      - "8000:80"
    networks:
      environment_network:
        ipv4_address: 172.30.0.3

  php-fpm:
    build: docker/php-fpm
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini
    networks:
      environment_network:
        ipv4_address: 172.30.0.4

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_USERNAME=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      environment_network:
        ipv4_address: 172.30.0.5

networks:
  environment_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
