version: "3.9"

services:
  ubuntu:
    build: .
    image: pansiere/ubuntu
    container_name: ubuntu_p
    hostname: ubuntu_p
    privileged: true
    volumes:
      - ubuntu_p:/data
    network_mode: host
    restart: always
    tty: true
    stdin_open: true

volumes:
  ubuntu_p:
    name: ubuntu_p
    driver: local
