version: "3.9"
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      network:
        ipv4_address: 172.29.0.2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_USER=phpmyadmin
      - PMA_PASSWORD=password
    ports:
      - "8080:80"
    networks:
      network:
        ipv4_address: 172.29.0.3

volumes:
  mysql-volume:
    driver: local

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
