version: "3.9"
services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      dbnetwork:
        ipv4_address: 172.30.0.2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin
    restart: always
    environment:
      - PMA_USER=jp
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      dbnetwork:
        ipv4_address: 172.30.0.3

volumes:
  mysql-volume:
    driver: local

networks:
  dbnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
