version: "3.1"
services:
  mysql:
    image: "mysql:8.0"
    container_name: mysql
    working_dir: /application
    volumes:
      - ".:/application"
      - "./.mysql-data/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=DB
    ports:
      - "3306:3306"
    networks:
      environment_network:
        ipv4_address: 172.29.0.2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "8080:80"
    networks:
      environment_network:
        ipv4_address: 172.29.0.5

networks:
  environment_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
