version: '3.8'
services:
  php_apache:
    container_name: php_apache
    hostname: php_apache
    image: php:8.3.7-apache-bookworm
    ports:
      - "80:80"
    volumes:
      - ./projeto:/var/www/html
    restart: always
    